// Package assets bundles the frontend templates, static resources and the
// vtracer SVG engine inside the fan-reubah binary (go:embed), so a single
// self-contained executable can serve the whole application without separate
// deploy steps.
//
// The embedded content is generated by scripts/prepare-embed.sh (or the CI /
// Docker build pipeline). On a fresh clone the directories only contain the
// KEEP placeholders so the module always compiles; callers fall back to the
// on-disk sources when the real assets are missing.
package assets

import (
	"embed"
	"io/fs"
	"runtime"
)

//go:embed web engine
var embedded embed.FS

// Web returns the embedded frontend tree ("web/templates", "web/static").
func Web() embed.FS {
	return embedded
}

// VtracerBinary returns the vtracer engine bytes built in for the current
// platform, or nil when no engine was embedded.
func VtracerBinary() []byte {
	if !HasVtracer() {
		return nil
	}
	switch runtime.GOARCH {
	case "amd64":
		b, _ := embedded.ReadFile("engine/vtracer_linux_amd64")
		return b
	case "arm64":
		b, _ := embedded.ReadFile("engine/vtracer_linux_arm64")
		return b
	}
	return nil
}

// HasVtracer reports whether the vtracer engine for the current platform is
// embedded, without loading the possibly large binary into memory.
func HasVtracer() bool {
	if runtime.GOOS != "linux" {
		return false
	}
	switch runtime.GOARCH {
	case "amd64":
		_, err := fs.Stat(embedded, "engine/vtracer_linux_amd64")
		return err == nil
	case "arm64":
		_, err := fs.Stat(embedded, "engine/vtracer_linux_arm64")
		return err == nil
	}
	return false
}
